# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sreenath PS
email: contact@sreetunks.in
phone: +91 7994749863
description: >- # this means to ignore newlines until "baseurl:"
  Personal Blog and Portfolio website of Sreenath PS,
  Game Programmer and Designer currently in Mumbai, IN
url: "http://sreetunks.in" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: jekyll-theme-console 
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - projects.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
