title: Sreenath PS
email: contact@sreetunks.in
phone: +91 7994749863
description: >-
  Personal Blog and Portfolio website of Sreenath PS,
  Game Programmer and Designer currently in Mumbai, IN
url: "http://sreetunks.in"
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-feed

header_pages:
  - about.md
  - projects.md

style: hacker
